jobs:
- name: blt-job-1
  plan:
  - get: git-resource
  - task: hello
    file: https://github.com/animatedmax/concourse-resources/blob/master/task.yml
resources:
- name: git-resource
  type: git
  source:
    uri: https://github.com/animatedmax/concourse-resources.git
