jobs:
- name: blt-job-1
  plan:
  - get: git-resource
  - get: docker-image-resource
  - task: hello
    file: git-resource/task.yml
resources:
- name: git-resource
  type: git
  source:
    uri: https://github.com/animatedmax/concourse-resources.git
- name: docker-image-resource
  type: docker-image
  source:
    repository: animatedmax/blt
